pages:
  stage: deploy
  image: "rust:latest"
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
  before_script:
    - export PATH="$PATH:$CARGO_HOME/bin"
    - mdbook --version || cargo install --debug mdbook
  script:
    - mdbook build docs/
    - mv docs/book public
  artifacts:
    paths:
      - public
  only:
  - tmp

